# Generated by Django 4.1 on 2022-10-24 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_laboratory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratory',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='slug'),
        ),
    ]
