# Generated by Django 4.1 on 2023-06-07 16:36

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_laboratory_slug'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='labmember',
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='laboratory',
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='labusertype',
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
    ]
