# Generated by Django 5.1.7 on 2025-03-26 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_labusertype_options'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratory',
            name='users',
        ),
        migrations.AlterUniqueTogether(
            name='labusertype',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='labusertype',
            name='laboratory',
        ),
        migrations.RemoveField(
            model_name='labusertype',
            name='permissions',
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, unique=True, verbose_name='user type')),
                ('group', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group', verbose_name='group')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.usertype', verbose_name='user type'),
        ),
        migrations.DeleteModel(
            name='LabMember',
        ),
        migrations.DeleteModel(
            name='LabUserType',
        ),
    ]
