# Generated by Django 5.1.7 on 2025-03-28 03:51

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_usertype_options'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usertype',
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='usertype',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
    ]
