from populate_account import *
from populate_lab_people import *
from populate_lab_test import *

if __name__ == '__main__':
    print("Executing populating script...")
    print(" - Populating Account: ")
    print("  + Populating UserType")
    populate_usertype()
    print("  + Populating User")
    populate_user(10)
    print("  + Populating Laboratory")
    populate_lab(20)
    print(" - Populating Lab: ")
    print("  + Populating HealthcareProvider")
    populate_provider()
    print("  + Populating Doctor")
    populate_doctor(100)
    print("  + Populating Patient")
    populate_patient(1000)
    print("  + Populating Protocol")
    populate_protocol(3000)
    print("  + Populating Sample")
    populate_sample()
    print("  + Populating LabTestGroup")
    populate_labtestgroup()
    print("  + Populating LabTest")
    populate_simple_labtest(300)
    populate_compuesto_labtest(40)
    print("  + Populating LabTestResult")
    populate_labtestresult()
    print("  + Populating Culture")
    populate_antibiogram()
    print("Populating complete!!!")
