# Generated by Django 4.1 on 2022-10-24 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory',
            name='slug',
            field=models.SlugField(default='1', max_length=100, verbose_name='slug'),
        ),
    ]
