# Generated by Django 4.1 on 2022-09-27 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laboratory',
            options={'verbose_name': 'laboratory', 'verbose_name_plural': 'laboratories'},
        ),
        migrations.AlterModelOptions(
            name='laboratoryusers',
            options={'verbose_name': 'Laboratory User', 'verbose_name_plural': 'Laboratory Users'},
        ),
        migrations.AddField(
            model_name='laboratory',
            name='url',
            field=models.URLField(default='http://www.labo.com', max_length=100, verbose_name='url'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='laboratoryusers',
            name='laboratory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.laboratory', verbose_name='laboratory'),
        ),
        migrations.AlterField(
            model_name='laboratoryusers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
