# Generated by Django 4.1 on 2022-09-27 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_laboratory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratory',
            name='url',
            field=models.URLField(max_length=100, verbose_name='URL'),
        ),
    ]
