# Generated by Django 4.1 on 2023-06-13 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labusertype',
            options={'permissions': (('list_labusertype', 'Can list lab user type'),), 'verbose_name': 'lab user type', 'verbose_name_plural': 'lab user types'},
        ),
    ]
