# Generated by Django 4.1 on 2022-09-28 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laboratory',
            old_name='users',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
