# Generated by Django 4.1 on 2022-09-29 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LaboratoryUsers',
            new_name='LabMembers',
        ),
    ]
