# Generated by Django 4.1 on 2022-10-06 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0004_alter_culture_resistance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culture',
            name='resistance',
            field=models.CharField(choices=[('', ''), ('0', 'Low'), ('1', 'Medium'), ('2', 'High'), ('3', 'Unknown')], default='', max_length=1, verbose_name='resistance'),
        ),
    ]
