# Generated by Django 4.1 on 2022-10-09 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0007_alter_labtest_sample_type_alter_sample_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Antibiogram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine', models.CharField(max_length=30, verbose_name='medicine')),
                ('resistance', models.CharField(choices=[('', ''), ('0', 'Sensitive'), ('1', 'Intermediate'), ('2', 'Resistant')], default='', max_length=1, verbose_name='resistance')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('labtest_result', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab.labtestresult', verbose_name='lab test result')),
            ],
            options={
                'verbose_name': 'antibiogram',
                'verbose_name_plural': 'antibiograms',
            },
        ),
        migrations.RemoveField(
            model_name='labtest',
            name='is_culture',
        ),
        migrations.RemoveField(
            model_name='protocol',
            name='has_cultures',
        ),
        migrations.AddField(
            model_name='labtest',
            name='is_antibiogram',
            field=models.BooleanField(default=False, verbose_name='antibiogram'),
        ),
        migrations.AddField(
            model_name='protocol',
            name='is_urgent',
            field=models.BooleanField(default=False, verbose_name='urgent'),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='sample_type',
            field=models.CharField(blank=True, choices=[('', ''), ('0', 'Blood'), ('1', 'Urine'), ('2', 'Vaginal discharge'), ('3', 'Semen'), ('4', 'Saliva'), ('5', 'Stool'), ('6', 'Other')], max_length=1, null=True, verbose_name='sample type'),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='ub',
            field=models.CharField(blank=True, max_length=10, verbose_name='UB'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id_number',
            field=models.CharField(max_length=30, verbose_name='ID number'),
        ),
        migrations.DeleteModel(
            name='Culture',
        ),
        migrations.AddField(
            model_name='antibiogram',
            name='protocol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab.protocol', verbose_name='protocol'),
        ),
    ]
