# Generated by Django 4.1 on 2022-11-10 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0009_alter_patient_age_alter_patient_birthday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('', ''), ('0', 'Male'), ('1', 'Female'), ('2', 'Non-Binary'), ('3', 'Other')], default='', max_length=1, null=True, verbose_name='gender'),
        ),
    ]
