# Generated by Django 4.1 on 2022-10-05 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocol',
            name='validation_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='validation time'),
        ),
    ]
