# Generated by Django 4.1 on 2022-10-06 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0005_alter_culture_resistance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('', ''), ('0', 'Male'), ('1', 'Female'), ('2', 'Non-Binary'), ('3', 'Other')], default='', max_length=1, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id_type',
            field=models.CharField(choices=[('0', 'DNI'), ('1', 'LE'), ('2', 'LC'), ('3', 'Passport'), ('4', 'Other')], default='0', max_length=1, verbose_name='ID type'),
        ),
    ]
