# Generated by Django 4.1 on 2022-11-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0010_alter_patient_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='healthcare_provider',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='healthcare provider'),
        ),
    ]
