# Generated by Django 4.1 on 2022-11-15 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0011_alter_patient_healthcare_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='healthcare_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab.healthcareprovider', verbose_name='healthcare provider'),
        ),
    ]
