# Generated by Django 4.1 on 2022-11-15 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0012_alter_patient_healthcare_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthcareprovider',
            name='name',
            field=models.CharField(max_length=120, unique=True, verbose_name='name'),
        ),
    ]
