# Generated by Django 4.1 on 2023-06-07 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0013_alter_healthcareprovider_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'permissions': (('list', 'can list patient'),), 'verbose_name': 'patient', 'verbose_name_plural': 'patients'},
        ),
    ]
