# Generated by Django 4.1 on 2023-06-07 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0014_alter_patient_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'permissions': (('list', 'Can list patient'),), 'verbose_name': 'patient', 'verbose_name_plural': 'patients'},
        ),
    ]
