# Generated by Django 4.1 on 2023-06-08 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0016_alter_patient_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'permissions': (('list_doctor', 'Can list doctor'),), 'verbose_name': 'doctor', 'verbose_name_plural': 'doctors'},
        ),
        migrations.AlterModelOptions(
            name='healthcareprovider',
            options={'permissions': (('list_healthcareprovider', 'Can list healthcare provider'),), 'verbose_name': 'healthcare provider', 'verbose_name_plural': 'healthcare providers'},
        ),
    ]
