# Generated by Django 4.1 on 2023-06-08 14:09

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0018_alter_healthcareprovider_name_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='healthcareprovider',
            name='unique_iexact_name',
        ),
        migrations.AddConstraint(
            model_name='healthcareprovider',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_iexact_name', violation_error_message='There is already another health provider with this name.'),
        ),
    ]
