# Generated by Django 4.1 on 2025-01-18 19:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0021_alter_patient_gender_alter_patient_id_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='antibiogram',
            options={'permissions': (('list_antibiogram', 'Can list antibiogram'),), 'verbose_name': 'antibiogram', 'verbose_name_plural': 'antibiograms'},
        ),
        migrations.AlterModelOptions(
            name='labtest',
            options={'permissions': (('list_labtest', 'Can list lab test'),), 'verbose_name': 'lab test', 'verbose_name_plural': 'lab tests'},
        ),
        migrations.AlterModelOptions(
            name='labtestgroup',
            options={'permissions': (('list_labtestgroup', 'Can list lab test group'),), 'verbose_name': 'lab test group', 'verbose_name_plural': 'lab test groups'},
        ),
        migrations.AlterModelOptions(
            name='labtestresult',
            options={'permissions': (('list_labtestresult', 'Can list lab test result'),), 'verbose_name': 'lab test result', 'verbose_name_plural': 'lab test results'},
        ),
        migrations.AlterModelOptions(
            name='protocol',
            options={'permissions': (('list_protocol', 'Can list protocol'),), 'verbose_name': 'protocol', 'verbose_name_plural': 'protocols'},
        ),
        migrations.AlterField(
            model_name='labtest',
            name='method',
            field=models.CharField(blank=True, max_length=50, verbose_name='method'),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='sample_type',
            field=models.CharField(blank=True, choices=[('', ''), ('0', 'Blood'), ('1', 'Urine'), ('2', 'Vaginal discharge'), ('3', 'Semen'), ('4', 'Saliva'), ('5', 'Stool'), ('6', 'Other')], default='', max_length=1, null=True, verbose_name='sample type'),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='unit',
            field=models.CharField(blank=True, max_length=50, verbose_name='unit'),
        ),
        migrations.AlterField(
            model_name='labtestgroup',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='checkin_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='check in time'),
        ),
    ]
